config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :genres
  root "movies#index"

  resources :users
  resource :session

  get 'register' => 'users#new'
  get "signin" => "sessions#new"  
  get "movies/filter/:scope" => "movies#index", as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favorites    
=======
  root "movies#index"
  resources :movies do
    resources :reviews
>>>>>>> 96de389ec1526b170b51680e81306b21b04dcdd1
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2016 Daniel Kent is Awesome.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Flix', root_path %></h1>
<<<<<<< HEAD
    <nav>
      <p>
        <% if current_user %>
          <%= link_to current_user.name, user_path(current_user) %>
          <%= link_to "Sign out", session_path, method: :delete, class: 'button' %>
        <% else %>
          <%= link_to 'Register', register_path, class: 'button' %>
          <%= link_to 'Sign in', signin_path, class: 'button' %>
        <% end %>
      </p>
    </nav>
  </div>  
=======
  </div>
>>>>>>> 96de389ec1526b170b51680e81306b21b04dcdd1
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-movies">
<<<<<<< HEAD
        <%= link_to 'Released', movies_path, class: 'button active' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Hits', filtered_movies_path(:hits), class: 'button' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Flops', filtered_movies_path(:flops), class: 'button' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Upcoming', filtered_movies_path(:upcoming), class: 'button' %>
      </li>
      <li class="all-movies">
        <%= link_to 'Recent', filtered_movies_path(:recent), class: 'button' %>
      </li>
      <% if current_user_admin? %>
        <li class="create-movie">
          <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
        </li>
      <% end %>
    </ul>
  </nav>

  <%= content_for(:side) %>
=======
        <%= link_to 'All Movies', movies_path, class: 'button' %>
      </li>
      <li class="create-movie">
        <%= link_to 'Add New Movie', new_movie_path, class: 'button' %>
      </li>
    </ul>
  </nav>
>>>>>>> 96de389ec1526b170b51680e81306b21b04dcdd1
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <title><%= page_title %></title>
=======
    <title>Super-Heroic Flix</title>
>>>>>>> 96de389ec1526b170b51680e81306b21b04dcdd1
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div id="wrapper">

      <%= render "layouts/flashes" %>
      
      <div id="container">
        <section id="sidebar">
          <%= render "layouts/sidebar" %>
        </section>
        <section id="content">
          <%= yield %>
        </section>
      </div>

    </div>

    <%= render "layouts/footer" %>
  </body>
</html>